spring:
  application:
    name: notification-service


  sleuth:
    integration:
      enabled: true

    sampler:
      probability: 1

  zipkin:
    base-url: http://localhost:9411/


  #kafka property
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeSerializer



#    generate-ddl: true
server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#actuator promethues endpoint
management:
  endpoints:
    web:
      exposure:
        include: prometheus