spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlineshopping
    username: "root"
    password: "root"

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  application:
    name: order-service

  jpa:
    hibernate.ddl-auto: update
  #kafka property
#  kafka:
#    bootstrap-servers: localhost:9092
#    template:
#      default-topic: notificationTopic
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#       spring.json.type.mapping:


#    generate-ddl: true
server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


#      Resilience4j Properties

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      inventory:
        baseConfig: default
  # Reslieance4j. timeout properties
  timelimiter:
    instances:
      inventory:
        timeoutDuration: 3s

  #        Reselience4j Retyr properties
  retry:
    instances:
      inventory:
        maxAttempts: 3
        waitDuration: 5s







