spring:
  application:
    name: api-gateway
  zipkin:
   base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0



server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO















